




site_name: AutoGRAMS Docs
site_url: https://autograms.github.io/autograms
docs_dir: docs
nav:
  - Home: index.md  
  - Documentation: 
      - Autogram class: documentation/autogram.md
      - Autograms Decorators: documentation/decorators.md
      - Managing memory: memory.md
      - Nodes: nodes.md
      - Reply functions: reply_functions.md
      - Decision functions: decision_functions.md
      - Generation functions: structured_generation_functions.md
      - Control Flow functions: control_flow_functions.md
      - Prompt functions: prompt_functions.md
      - Models calling functions: model_functions.md
      - Embedding functions: embeddings.md
      - Logging functions: logging_functions.md
      - Code utility functions: helper.md





theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

extra_javascript:
  - extra.js

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/autograms/autograms
    


